name: Build (and dockerize) reqex # This is a GENERIC deploy rust thing to docker.
on: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
  push:
    branches: [ $default-branch ]
    tags: # This builds for all branches with semantically versioned tags (v0.12.3).
      - v* # https://semver.org will fail, if there are any other tags

env:
  PACKAGE_NAME: ${{ github.event.repository.name }}

jobs: # https://github.com/actions/starter-workflows/blob/700743e33258dd9548184fb98497da9fb75c5b31/ci/rust.yml
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1 # https://github.com/actions-rs/toolchain
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1 # https://github.com/Swatinem/rust-cache

      - uses: actions-rs/cargo@v1 # https://github.com/actions-rs/cargo
        with:
          command: build
          args: --release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: target/release/${{ env.PACKAGE_NAME }}
